In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Employee_ID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Amit","Priya","Rahul","Sneha","Arjun",
            "Kiran","Neha","Ravi","Pooja","Manoj"],
    "Department":["IT","HR","IT","Finance","HR",
                  "IT","Finance","HR","IT","Finance"],
    "Experience":[2,5,None,3,7,1,None,4,6,2],
    "Salary":[45000,60000,55000,None,75000,
              40000,65000,58000,None,52000]
}

df = pd.DataFrame(data)

df.to_csv("employees.csv", index=False)

print("employees.csv created")

employees.csv created

In [4]:
df=pd.read_csv("employees.csv")

In [5]:
df

   Employee_ID   Name Department  Experience   Salary
0          101   Amit         IT         2.0  45000.0
1          102  Priya         HR         5.0  60000.0
2          103  Rahul         IT         NaN  55000.0
3          104  Sneha    Finance         3.0      NaN
4          105  Arjun         HR         7.0  75000.0
5          106  Kiran         IT         1.0  40000.0
6          107   Neha    Finance         NaN  65000.0
7          108   Ravi         HR         4.0  58000.0
8          109  Pooja         IT         6.0      NaN
9          110  Manoj    Finance         2.0  52000.0

In [6]:
df.isnull()

   Employee_ID   Name  Department  Experience  Salary
0        False  False       False       False   False
1        False  False       False       False   False
2        False  False       False        True   False
3        False  False       False       False    True
4        False  False       False       False   False
5        False  False       False       False   False
6        False  False       False        True   False
7        False  False       False       False   False
8        False  False       False       False    True
9        False  False       False       False   False

In [7]:
df.isnull().sum()

Employee_ID    0
Name           0
Department     0
Experience     2
Salary         2
dtype: int64